USE [master]
GO

ALTER DATABASE [SnapDMS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE [SnapDMS];

ALTER DATABASE [dw] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE [dw];

ALTER DATABASE [dw_test] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE [dw_test];