version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "appflow-custom"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1inoibnenkdu2"
s3_prefix = "appflow-custom"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
